# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_history import DriverHistory  # noqa: F401,E501
from swagger_server.models.personal_details import PersonalDetails  # noqa: F401,E501
from swagger_server import util


class DriverDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, personal_details: PersonalDetails=None, driver_history: DriverHistory=None):  # noqa: E501
        """DriverDetails - a model defined in Swagger

        :param id: The id of this DriverDetails.  # noqa: E501
        :type id: int
        :param personal_details: The personal_details of this DriverDetails.  # noqa: E501
        :type personal_details: PersonalDetails
        :param driver_history: The driver_history of this DriverDetails.  # noqa: E501
        :type driver_history: DriverHistory
        """
        self.swagger_types = {
            'id': int,
            'personal_details': PersonalDetails,
            'driver_history': DriverHistory
        }

        self.attribute_map = {
            'id': 'id',
            'personal_details': 'personal_details',
            'driver_history': 'driver_history'
        }
        self._id = id
        self._personal_details = personal_details
        self._driver_history = driver_history

    @classmethod
    def from_dict(cls, dikt) -> 'DriverDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DriverDetails of this DriverDetails.  # noqa: E501
        :rtype: DriverDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this DriverDetails.


        :return: The id of this DriverDetails.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this DriverDetails.


        :param id: The id of this DriverDetails.
        :type id: int
        """

        self._id = id

    @property
    def personal_details(self) -> PersonalDetails:
        """Gets the personal_details of this DriverDetails.


        :return: The personal_details of this DriverDetails.
        :rtype: PersonalDetails
        """
        return self._personal_details

    @personal_details.setter
    def personal_details(self, personal_details: PersonalDetails):
        """Sets the personal_details of this DriverDetails.


        :param personal_details: The personal_details of this DriverDetails.
        :type personal_details: PersonalDetails
        """

        self._personal_details = personal_details

    @property
    def driver_history(self) -> DriverHistory:
        """Gets the driver_history of this DriverDetails.


        :return: The driver_history of this DriverDetails.
        :rtype: DriverHistory
        """
        return self._driver_history

    @driver_history.setter
    def driver_history(self, driver_history: DriverHistory):
        """Sets the driver_history of this DriverDetails.


        :param driver_history: The driver_history of this DriverDetails.
        :type driver_history: DriverHistory
        """

        self._driver_history = driver_history
