# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.home_details import HomeDetails  # noqa: F401,E501
from swagger_server.models.personal_details import PersonalDetails  # noqa: F401,E501
from swagger_server import util


class HomeQuoteSections(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, personal_details: PersonalDetails=None, home_details: HomeDetails=None):  # noqa: E501
        """HomeQuoteSections - a model defined in Swagger

        :param personal_details: The personal_details of this HomeQuoteSections.  # noqa: E501
        :type personal_details: PersonalDetails
        :param home_details: The home_details of this HomeQuoteSections.  # noqa: E501
        :type home_details: HomeDetails
        """
        self.swagger_types = {
            'personal_details': PersonalDetails,
            'home_details': HomeDetails
        }

        self.attribute_map = {
            'personal_details': 'personal_details',
            'home_details': 'home_details'
        }
        self._personal_details = personal_details
        self._home_details = home_details

    @classmethod
    def from_dict(cls, dikt) -> 'HomeQuoteSections':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomeQuoteSections of this HomeQuoteSections.  # noqa: E501
        :rtype: HomeQuoteSections
        """
        return util.deserialize_model(dikt, cls)

    @property
    def personal_details(self) -> PersonalDetails:
        """Gets the personal_details of this HomeQuoteSections.


        :return: The personal_details of this HomeQuoteSections.
        :rtype: PersonalDetails
        """
        return self._personal_details

    @personal_details.setter
    def personal_details(self, personal_details: PersonalDetails):
        """Sets the personal_details of this HomeQuoteSections.


        :param personal_details: The personal_details of this HomeQuoteSections.
        :type personal_details: PersonalDetails
        """

        self._personal_details = personal_details

    @property
    def home_details(self) -> HomeDetails:
        """Gets the home_details of this HomeQuoteSections.


        :return: The home_details of this HomeQuoteSections.
        :rtype: HomeDetails
        """
        return self._home_details

    @home_details.setter
    def home_details(self, home_details: HomeDetails):
        """Sets the home_details of this HomeQuoteSections.


        :param home_details: The home_details of this HomeQuoteSections.
        :type home_details: HomeDetails
        """

        self._home_details = home_details
