# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, authenticated: bool=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param user_id: The user_id of this InlineResponse200.  # noqa: E501
        :type user_id: int
        :param authenticated: The authenticated of this InlineResponse200.  # noqa: E501
        :type authenticated: bool
        """
        self.swagger_types = {
            'user_id': int,
            'authenticated': bool
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'authenticated': 'authenticated'
        }
        self._user_id = user_id
        self._authenticated = authenticated

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this InlineResponse200.


        :return: The user_id of this InlineResponse200.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this InlineResponse200.


        :param user_id: The user_id of this InlineResponse200.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def authenticated(self) -> bool:
        """Gets the authenticated of this InlineResponse200.


        :return: The authenticated of this InlineResponse200.
        :rtype: bool
        """
        return self._authenticated

    @authenticated.setter
    def authenticated(self, authenticated: bool):
        """Sets the authenticated of this InlineResponse200.


        :param authenticated: The authenticated of this InlineResponse200.
        :type authenticated: bool
        """

        self._authenticated = authenticated
