# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.insurance_type import InsuranceType  # noqa: F401,E501
from swagger_server import util


class QuoteSections(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quote_id: int=None, quote_type: InsuranceType=None):  # noqa: E501
        """QuoteSections - a model defined in Swagger

        :param quote_id: The quote_id of this QuoteSections.  # noqa: E501
        :type quote_id: int
        :param quote_type: The quote_type of this QuoteSections.  # noqa: E501
        :type quote_type: InsuranceType
        """
        self.swagger_types = {
            'quote_id': int,
            'quote_type': InsuranceType
        }

        self.attribute_map = {
            'quote_id': 'quote_id',
            'quote_type': 'quote_type'
        }
        self._quote_id = quote_id
        self._quote_type = quote_type

    @classmethod
    def from_dict(cls, dikt) -> 'QuoteSections':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QuoteSections of this QuoteSections.  # noqa: E501
        :rtype: QuoteSections
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quote_id(self) -> int:
        """Gets the quote_id of this QuoteSections.


        :return: The quote_id of this QuoteSections.
        :rtype: int
        """
        return self._quote_id

    @quote_id.setter
    def quote_id(self, quote_id: int):
        """Sets the quote_id of this QuoteSections.


        :param quote_id: The quote_id of this QuoteSections.
        :type quote_id: int
        """

        self._quote_id = quote_id

    @property
    def quote_type(self) -> InsuranceType:
        """Gets the quote_type of this QuoteSections.


        :return: The quote_type of this QuoteSections.
        :rtype: InsuranceType
        """
        return self._quote_type

    @quote_type.setter
    def quote_type(self, quote_type: InsuranceType):
        """Sets the quote_type of this QuoteSections.


        :param quote_type: The quote_type of this QuoteSections.
        :type quote_type: InsuranceType
        """

        self._quote_type = quote_type
