# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.membership import Membership  # noqa: F401,E501
from swagger_server.models.role import Role  # noqa: F401,E501
from swagger_server import util


class UserProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, name: str=None, role: Role=None, points: int=None, membership: Membership=None):  # noqa: E501
        """UserProfile - a model defined in Swagger

        :param user_id: The user_id of this UserProfile.  # noqa: E501
        :type user_id: int
        :param name: The name of this UserProfile.  # noqa: E501
        :type name: str
        :param role: The role of this UserProfile.  # noqa: E501
        :type role: Role
        :param points: The points of this UserProfile.  # noqa: E501
        :type points: int
        :param membership: The membership of this UserProfile.  # noqa: E501
        :type membership: Membership
        """
        self.swagger_types = {
            'user_id': int,
            'name': str,
            'role': Role,
            'points': int,
            'membership': Membership
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'name': 'name',
            'role': 'role',
            'points': 'points',
            'membership': 'membership'
        }
        self._user_id = user_id
        self._name = name
        self._role = role
        self._points = points
        self._membership = membership

    @classmethod
    def from_dict(cls, dikt) -> 'UserProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserProfile of this UserProfile.  # noqa: E501
        :rtype: UserProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this UserProfile.


        :return: The user_id of this UserProfile.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this UserProfile.


        :param user_id: The user_id of this UserProfile.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def name(self) -> str:
        """Gets the name of this UserProfile.


        :return: The name of this UserProfile.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserProfile.


        :param name: The name of this UserProfile.
        :type name: str
        """

        self._name = name

    @property
    def role(self) -> Role:
        """Gets the role of this UserProfile.


        :return: The role of this UserProfile.
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role: Role):
        """Sets the role of this UserProfile.


        :param role: The role of this UserProfile.
        :type role: Role
        """

        self._role = role

    @property
    def points(self) -> int:
        """Gets the points of this UserProfile.


        :return: The points of this UserProfile.
        :rtype: int
        """
        return self._points

    @points.setter
    def points(self, points: int):
        """Sets the points of this UserProfile.


        :param points: The points of this UserProfile.
        :type points: int
        """

        self._points = points

    @property
    def membership(self) -> Membership:
        """Gets the membership of this UserProfile.


        :return: The membership of this UserProfile.
        :rtype: Membership
        """
        return self._membership

    @membership.setter
    def membership(self, membership: Membership):
        """Sets the membership of this UserProfile.


        :param membership: The membership of this UserProfile.
        :type membership: Membership
        """

        self._membership = membership
