openapi: 3.0.1
info:
  title: Pet Store
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: pet
paths:
  /pet/{pet_id}:
    get:
      tags:
      - pet
      summary: Get a pet in the store
      operationId: get_pet
      parameters:
      - name: pet_id
        in: path
        description: The id of the pet to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully retrived pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        404:
          description: Pet doesn't exist
          content: {}
      x-swagger-router-controller: web.controllers.pets_controller
    put:
      tags:
      - pet
      summary: Update and replace a pet in the store
      operationId: update_pet
      parameters:
      - name: pet_id
        in: path
        description: The id of the pet to update from the store
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        200:
          description: Successfully updated pet
          content: {}
        404:
          description: Pet doesn't exist
          content: {}
      x-swagger-router-controller: web.controllers.pets_controller
      x-codegen-request-body-name: Pet
    delete:
      tags:
      - pet
      summary: Remove a pet in the store
      operationId: remove_pet
      parameters:
      - name: pet_id
        in: path
        description: The id of the pet to remove from the store
        required: true
        schema:
          type: string
      responses:
        202:
          description: Successfully deleted pet
          content: {}
        404:
          description: Pet doesn't exist
          content: {}
      x-swagger-router-controller: web.controllers.pets_controller
  /pet:
    get:
      tags:
      - pet
      summary: Gets all pets in the store
      operationId: get_all_pets
      responses:
        200:
          description: Successfully received all pets.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
      x-swagger-router-controller: controllers.pets_controller
    post:
      tags:
      - pet
      summary: Add a new pet to the store
      operationId: add_pet
      requestBody:
        description: Pet to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        201:
          description: Pet added
          content: {}
      x-swagger-router-controller: web.controllers.pets_controller
      x-codegen-request-body-name: body
components:
  schemas:
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
    Pet:
      required:
      - breed
      - name
      - price
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        breed:
          type: string
        price:
          type: number
          format: float
      example:
        id: 1
        name: doggie
        breed: German Shepherd
        price: 100.0
