/**
 * Smart Insurance System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HomeDetails } from './homeDetails';
import { InsuranceType } from './insuranceType';
import { PersonalDetails } from './personalDetails';
import { QuoteSections } from './quoteSections';

export interface HomeQuoteSections extends QuoteSections { 
    personalDetails?: PersonalDetails;
    homeDetails?: HomeDetails;
}