/**
 * Smart Insurance System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PreviousClaim { 
    id?: number;
    driverHistoryId?: number;
    date?: string;
    fault?: PreviousClaim.FaultEnum;
    claimType?: PreviousClaim.ClaimTypeEnum;
}
export namespace PreviousClaim {
    export type FaultEnum = 'Self' | 'ThirdParty';
    export const FaultEnum = {
        Self: 'Self' as FaultEnum,
        ThirdParty: 'ThirdParty' as FaultEnum
    };
    export type ClaimTypeEnum = 'Accident' | 'Theft';
    export const ClaimTypeEnum = {
        Accident: 'Accident' as ClaimTypeEnum,
        Theft: 'Theft' as ClaimTypeEnum
    };
}