/**
 * Smart Insurance System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HomeQuoteSections } from './homeQuoteSections';
import { InsuranceType } from './insuranceType';
import { VehicleQuoteSections } from './vehicleQuoteSections';

export interface Quote { 
    id?: number;
    userId?: number;
    type: InsuranceType;
    created?: number;
    updated?: number;
    isComplete?: boolean;
    price?: number;
    sections?: VehicleQuoteSections | HomeQuoteSections;
}