/**
 * Smart Insurance System
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DriverDetails } from './driverDetails';
import { InsuranceType } from './insuranceType';
import { QuoteSections } from './quoteSections';
import { VehicleDetails } from './vehicleDetails';
import { VehicleUsage } from './vehicleUsage';

export interface VehicleQuoteSections extends QuoteSections { 
    driverDetails?: DriverDetails;
    vehicleDetails?: VehicleDetails;
    vehicleUsage?: VehicleUsage;
    additionalDrivers?: Array<DriverDetails>;
}