# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.insurance_package_api import InsurancePackageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInsurancePackageApi(unittest.TestCase):
    """InsurancePackageApi unit test stubs"""

    def setUp(self):
        self.api = InsurancePackageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_package(self):
        """Test case for create_package

        Create new package  # noqa: E501
        """
        pass

    def test_delete_package(self):
        """Test case for delete_package

        Delete application  # noqa: E501
        """
        pass

    def test_get_active(self):
        """Test case for get_active

        Get active packages  # noqa: E501
        """
        pass

    def test_get_all(self):
        """Test case for get_all

        Gets all packages for a user  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update package  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
