# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_profile_api import UserProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserProfileApi(unittest.TestCase):
    """UserProfileApi unit test stubs"""

    def setUp(self):
        self.api = UserProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_profile(self):
        """Test case for create_profile

        Create a user profile  # noqa: E501
        """
        pass

    def test_get_profile(self):
        """Test case for get_profile

        Get a user profile  # noqa: E501
        """
        pass

    def test_remove_profile(self):
        """Test case for remove_profile

        Remove a user profile  # noqa: E501
        """
        pass

    def test_update_profile(self):
        """Test case for update_profile

        Update and replace a user profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
