# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.benefits import Benefits  # noqa: E501
from swagger_client.rest import ApiException


class TestBenefits(unittest.TestCase):
    """Benefits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBenefits(self):
        """Test Benefits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.benefits.Benefits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
