# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.claims_api import ClaimsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClaimsApi(unittest.TestCase):
    """ClaimsApi unit test stubs"""

    def setUp(self):
        self.api = ClaimsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_for_package(self):
        """Test case for get_for_package

        Get all claims for a package  # noqa: E501
        """
        pass

    def test_get_for_user(self):
        """Test case for get_for_user

        Get all claims for a user  # noqa: E501
        """
        pass

    def test_get_one(self):
        """Test case for get_one

        Get all claims for a package  # noqa: E501
        """
        pass

    def test_new_claim(self):
        """Test case for new_claim

        Create a new claim  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
