# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.claim_history_api import ClaimHistoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClaimHistoryApi(unittest.TestCase):
    """ClaimHistoryApi unit test stubs"""

    def setUp(self):
        self.api = ClaimHistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_note(self):
        """Test case for add_note

        Add note  # noqa: E501
        """
        pass

    def test_get_history(self):
        """Test case for get_history

        Get history for a claim  # noqa: E501
        """
        pass

    def test_get_note(self):
        """Test case for get_note

        Get claim note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
