# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.insurance_package_type import InsurancePackageType  # noqa: E501
from swagger_client.rest import ApiException


class TestInsurancePackageType(unittest.TestCase):
    """InsurancePackageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsurancePackageType(self):
        """Test InsurancePackageType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.insurance_package_type.InsurancePackageType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
