# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_server.models.base_model_ import Model
from api_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, email: str=None, password_hash: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param password_hash: The password_hash of this User.  # noqa: E501
        :type password_hash: str
        """
        self.swagger_types = {
            'id': int,
            'email': str,
            'password_hash': str
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'password_hash': 'password_hash'
        }
        self._id = id
        self._email = email
        self._password_hash = password_hash

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password_hash(self) -> str:
        """Gets the password_hash of this User.


        :return: The password_hash of this User.
        :rtype: str
        """
        return self._password_hash

    @password_hash.setter
    def password_hash(self, password_hash: str):
        """Sets the password_hash of this User.


        :param password_hash: The password_hash of this User.
        :type password_hash: str
        """

        self._password_hash = password_hash
