# coding: utf-8

# flake8: noqa
"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.attachment import Attachment
from swagger_client.models.attachments import Attachments
from swagger_client.models.benefit import Benefit
from swagger_client.models.benefits import Benefits
from swagger_client.models.claim import Claim
from swagger_client.models.claim_history import ClaimHistory
from swagger_client.models.claim_note import ClaimNote
from swagger_client.models.claim_status import ClaimStatus
from swagger_client.models.claims import Claims
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.insurance_package import InsurancePackage
from swagger_client.models.insurance_package_type import InsurancePackageType
from swagger_client.models.insurance_packages import InsurancePackages
from swagger_client.models.membership import Membership
from swagger_client.models.membership_type import MembershipType
from swagger_client.models.role import Role
from swagger_client.models.user import User
from swagger_client.models.user_profile import UserProfile
