# coding: utf-8

"""
    Smart Insurance System

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InsurancePackage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'type': 'InsurancePackageType',
        'start_date': 'date',
        'end_date': 'date'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'type': 'type',
        'start_date': 'start_date',
        'end_date': 'end_date'
    }

    def __init__(self, id=None, user_id=None, type=None, start_date=None, end_date=None):  # noqa: E501
        """InsurancePolicy - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._type = None
        self._start_date = None
        self._end_date = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if user_id is not None:
            self.user_id = user_id
        if type is not None:
            self.type = type
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date

    @property
    def id(self):
        """Gets the id of this InsurancePolicy.  # noqa: E501


        :return: The id of this InsurancePolicy.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InsurancePolicy.


        :param id: The id of this InsurancePolicy.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this InsurancePolicy.  # noqa: E501


        :return: The user_id of this InsurancePolicy.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InsurancePolicy.


        :param user_id: The user_id of this InsurancePolicy.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def type(self):
        """Gets the type of this InsurancePolicy.  # noqa: E501


        :return: The type of this InsurancePolicy.  # noqa: E501
        :rtype: InsurancePackageType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InsurancePolicy.


        :param type: The type of this InsurancePolicy.  # noqa: E501
        :type: InsurancePackageType
        """

        self._type = type

    @property
    def start_date(self):
        """Gets the start_date of this InsurancePolicy.  # noqa: E501


        :return: The start_date of this InsurancePolicy.  # noqa: E501
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this InsurancePolicy.


        :param start_date: The start_date of this InsurancePolicy.  # noqa: E501
        :type: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this InsurancePolicy.  # noqa: E501


        :return: The end_date of this InsurancePolicy.  # noqa: E501
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this InsurancePolicy.


        :param end_date: The end_date of this InsurancePolicy.  # noqa: E501
        :type: date
        """

        self._end_date = end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InsurancePackage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InsurancePackage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
